#!/usr/bin/env bash
# openbox autostart

AUTOSTART=(clipit pulseaudio tint2 volumeicon xcompmgr xscreensaver)

for APP in ${AUTOSTART[@]}; do
  if $(which ${APP} >/dev/null 2>&1); then
    ${APP} &
  fi
done
