#!/usr/bin/env bash
# openbox autostart

# autostart applications
AUTOSTART=(clipit pulseaudio tint2 xcompmgr xscreensaver)

for APP in ${AUTOSTART[@]}; do
  if $(which ${APP} >/dev/null 2>&1); then
    ${APP} &
  fi
done

# configurations
xset b off
